[package]
name = "simple-mdns"
version = "0.1.0"
authors = ["Ilson Roberto Balliego Junior <ilson.balliego@gmail.com>"]
edition = "2018"
description = "Rust implementation of mDNS for service discovering (DNS-SD)"
repository = "https://github.com/balliegojr/simple-dns"
license= "MIT"
keywords = ["dns", "dns-sd", "mdns", "service-discovery", "zeroconf"]
categories = ["network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-dns = "^0.1"
futures = "0.3.12"
socket2 = { version="0.3.19", features=["reuseport"] }
tokio = { version="^1.0", features=["full"] }
rand = "0.8.0"
log = "^0.4"
thiserror = "1.0.24"
lazy_static = "1.4.0"

[dev-dependencies]
tokio-test = "0.4.2"
